{{- range $role := .Values.roles }}
{{- if $role.rules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $role.name }}
rules: 
{{- toYaml $role.rules | nindent 2}}
---
{{ end }}
{{ end }}