apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.service }}
spec:
  selector:
    app: {{ .Values.names.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.ports.exposedPort }}
      targetPort: {{ .Values.ports.containerPort }}